# spring:
#   datasource:
#     url: "jdbc:postgresql://db:5432/hapi"
#     username: admin
#     password: admin
#     driverClassName: org.postgresql.Driver
#   jpa:
#     properties:
#       hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
#       hibernate.search.enabled: false
spring:
  logging:
    level:
      org.springframework: DEBUG
      ca.uhn.fhir: DEBUG
hapi:
  fhir:
    openapi_enabled: true
    custom-bean-packages: org.example,org.gematik
    custom-interceptor-classes: org.example.BearerAuthInterceptor,org.gematik.TestInterceptor
    custom-operation-classes: org.gematik.AcceptOperation
    implementationguides:
      kbv_ita_erp:
        packageUrl: https://packages.simplifier.net/kbv.ita.erp/-/kbv.ita.erp-1.1.2.tgz
        name: kbv.ita.erp
        version: 1.1.2
      kbv_basis:
        packageUrl: https://packages.simplifier.net/kbv.basis/-/kbv.basis-1.3.0.tgz
        name: kbv.basis
        version: 1.3.0
      kbv_ita_for:
        packageUrl: https://packages.simplifier.net/kbv.ita.for/-/kbv.ita.for-1.1.0.tgz
        name: kbv.ita.for
        version: 1.1.0
      de_basisprofil_r4:
        packageUrl: https://packages.simplifier.net/de.basisprofil.r4/-/de.basisprofil.r4-1.5.0.tgz
        name: de.basisprofil.r4
        version: 1.5.0
      de_gematik_epa_medication:
        packageUrl: https://packages.simplifier.net/de.gematik.epa.medication/-/de.gematik.epa.medication-1.1.1.tgz
        name: de.gematik.epa.medication
        version: 1.1.1
      kbv_all_st:
        packageUrl: https://packages.simplifier.net/kbv.all.st/-/kbv.all.st-1.4.0.tgz
        name: kbv.all.st
        version: 1.4.0
      de_gematik_fhir_directory:
        packageUrl: https://packages.simplifier.net/de.gematik.fhir.directory/-/de.gematik.fhir.directory-0.11.12.tgz
        name: de.gematik.fhir.directory
        version: 0.11.12
      de_ihe_d_terminology:
        packageUrl: https://packages.simplifier.net/de.ihe-d.terminology/-/de.ihe-d.terminology-3.0.0.tgz
        name: de.ihe-d.terminology
        version: 3.0.0
      de_gematik_terminology:
        packageUrl: https://packages.simplifier.net/de.gematik.terminology/-/de.gematik.terminology-1.0.1.tgz
        name: de.gematik.terminology
        version: 1.0.1
      de_gematik_epa:
        packageUrl: https://packages.simplifier.net/de.gematik.epa/-/de.gematik.epa-1.1.0.tgz
        name: de.gematik.epa
        version: 1.1.0
